[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.2.0"
authors = ["tkcd<goriponikeike55@gmail.com>"]
edition = "2024"
rust-version = "1.94"
repository = "https://github.com/takeshid/typua"
license = "MIT"

[workspace.dependencies]
# internal dependencies
typua_cli = { path = "crates/typua_cli" }
typua_config = { path = "crates/typua_config" }
typua_hir = { path = "crates/typua_hir" }
typua_syntax = { path = "crates/typua_syntax" }
typua_types = { path = "crates/typua_types" }

# external dependencies
## for release
anyhow = "1"
clap = { version = "4", features = ["derive"] }
full_moon = { version = "2", features = ["luajit"] }
indexmap = "2.12"
itertools = "0.14"
nom = "8.0.0"
nom_locate = "5.0.0"
rustc-hash = "2.1"
serde = "1.0"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tokio-macros = "2.6"
tower-lsp-server = "0.23"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
dirs = "6"
tempfile = "3"

## for development
pretty_assertions = "1.4"
unindent = "0.2"
