[package]
name = "typua_syntax"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
# internal
typua_config.workspace = true
typua_types.workspace = true

# external
full_moon.workspace = true
nom.workspace = true
nom_locate.workspace = true
tracing.workspace = true
tower-lsp-server.workspace = true

[dev-dependencies]
unindent.workspace = true
pretty_assertions.workspace = true
