[package]
name = "typua_cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "typua"
path = "src/main.rs"

[dependencies]
clap.workspace = true
typua_config.workspace = true
typua_hir.workspace = true

[dev-dependencies]
tempfile.workspace = true
