[package]
name = "typua_hir"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# internal
typua_syntax.workspace = true
typua_types.workspace = true
typua_config.workspace = true

# external
rustc-hash.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
unindent.workspace = true
